name: Auto approve
on:
  pull_request_target:
    types:
      - review_requested

jobs:
  approve:
    if: |
      github.event.pull_request.user.login == github.repository_owner && ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
